### ISSUE TITLE
OpenAltimetry Version 2.0

### ISSUE THREAD

**Issue by mollystroud** [mlampros/IceSat2R#13]
Many functions in the IceSat2R package no longer work as the OpenAltimetry website (previously https://openaltimetry.org/) appears to have migrated to https://openaltimetry.earthdatacloud.nasa.gov/ in their new Version 2.0 release (released October 5th, see [https://nsidc.org/openaltimetry/known-issues-updates#anchor-0]. The URLs accessed in most functions no longer load.

For example, when attempting to use getTracks(), which accesses openaltimetry.org/data/api/icesat2/getTracks....., the function fails with the following error: "Timeout was reached: [openaltimetry.org] Connection timeout after 10005 ms"

Will there be any updates to keep IceSat2R working with the new OpenAltimetry version 2.0?

Thank you!

**Comment by mlampros** [comment]
@mollystroud thank you for making me aware of this migration to  https://openaltimetry.earthdatacloud.nasa.gov/
It seems there is no easy access as previously to the IceSat-2 data (using the https://openaltimetry.org/ API and infrastructure). Which means I might have to re-write the code base. Are you aware of an API interface of this new website for IceSat-2 data?

**Comment by mollystroud** [comment]
@mlampros Unfortunately I'm not aware of one, but I haven't searched for it. Thank you for your prompt response.

**Comment by mlampros** [comment]
@mlampros thank you. I'll keep this issue open.

**Comment by mlampros** [comment]
I sent an e-mail to NSIDC User Services, and I received a response (2023-10-17) mentioning that the api interface (now hosted in NASA's Earthdata Cloud) will work soon, hopefully in the next couple of weeks.
