### ISSUE TITLE
Suggestion `chmod -R 777 /home/YOUR_DIR`

### ISSUE THREAD

**Issue by evetion** [mlampros/IceSat2R#6]
In your documentation you suggest to `chmod -R 777 /home/YOUR_DIR`, but this is a bad practice, as it opens up your (private) homedir to everyone (including write permissions) on your computer. I'm not sure what issues you ran into, but it's better to refer to the Docker manual (https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) for such things.

**Comment by mlampros** [comment]
Thanks for mentioning it. I updated the README.md file
